### ISSUE TITLE
Explicit "v1" in URLs

### ISSUE THREAD

**Issue by dginev** [dginev/ar5iv#10]
Jess Riedel was sadly [taken for a ride](https://twitter.com/Jess_Riedel/status/1488256624909189124) by ar5iv not making it clear we only have "v1" of each article.

Rather than drop the version, we should have it always appended, and even send a clear warning when redirecting from "v2", "v3", ... "vN" down to "v1" on the lines of:

> "Hey there! ar5iv only has access to the v1 source of all articles. This may be different than what you expect to find."

**Comment by JessRiedel** [comment]
I very much appreciate that ar5iv may be going for a clean minimal look by not having a header (only a footer) on the article pages, which places the content front and center.  However, my weak opinion is that these pages would be better with a header that had, at the least, (1) some sort of indicator of the version number at the top of the page would be appropriate (much as the arXiv stamps the version on the left margin of each PDF), and (2) a link to the original arXiv version (which is currently in the footer).

Thank you for this useful service.

**Comment by dginev** [comment]
I ended up stalling here due to the report in [#45](https://github.com/dginev/ar5iv/issues/45#issuecomment-1030619999) , where it became apparent not all distributed sources are v1.

I would definitely lean towards not causing additional confusion by claiming a later version is `v1`. The best way forward may be to actually bite the bullet and implement serving the "latest version" from arXiv, but that is a feature best done with the support of the arXiv stack, and ideally from inside rather than outside. I'll sit on the question for another week, as I expect a few additional puzzle pieces to fall into place soon.

**Comment by dginev** [comment]
And now I'm going to outright close here and say there is a serious "intention" to get the latest versions in the "weeks" time frame. More details will follow shortly... 

Anyone interested is invited to shift their attention to #48
