### ISSUE TITLE
Improve article 2007.01282

### ISSUE THREAD

**Issue by So-Byeonghoon** [dginev/ar5iv#103]
**Exact location of issue**
Figure 2. in original article is missing.
It was located in [Section 1](https://ar5iv.labs.arxiv.org/html/2007.01282#S1) in main.tex file.

**Problem details**
Figure 2. in original article is missing in html version.
It is `FiD3.pdf` file of the source.

**(Optional) Expected behavior**
Figure 2. should be loaded.

**Desktop (please complete the following information)**
 - OS: macOS
 - Browser: chrome

**(Optional) Screenshots**
<img width="788" alt="image" src="https://user-images.githubusercontent.com/9799221/156874647-c8719965-6192-489c-90e8-06fecb7fa5e9.png">

**Comment by dginev** [comment]
Hi @So-Byeonghoon ,

I'm sorry to say this is another case of ar5iv serving only the first version of an arXiv article (see #48 for the tracking issue on upgrading that).

If you examine the [PDF for 2007.01282v1](https://arxiv.org/pdf/2007.01282v1.pdf), the figure you mention simply isn't in it yet. It was introduced in `v2` of that article.

Once we are able to update to the latest sources, this will be auto-resolved.
