### ISSUE TITLE
Improve article 1608.05377 (\rangle not rendering on mobile)

### ISSUE THREAD

**Issue by JessRiedel** [dginev/ar5iv#11]
**Exact location of issue**
https://ar5iv.org/html/1608.05377#S0.F1

**Problem details**

The latex \rangle math symbol isn't rendering on mobile (at least for Chrome and Safari, iPhone 12, iOS 15.2.1).  For example, it should appear where the red circles are:

![IMG_0534](https://user-images.githubusercontent.com/16365564/151888752-405769ed-3f5c-4cee-8bf2-d2a3e59bb7f5.jpg)

This occurs in many places in the paper.

**Expected behavior**

This math is displayed correctly on desktop:

<img width="684" alt="Screen Shot 2022-01-31 at 3 18 47 PM" src="https://user-images.githubusercontent.com/16365564/151888968-93ee58ed-89b0-44f5-9c90-b04200a87c63.png">

Note that this problem doesn't appear on either the mobile or desktop versions of the [arxiv-vanity rendering of this paper](https://www.arxiv-vanity.com/papers/1608.05377/).  Interestingly, arxiv-vanity has some errors of its own for this paper which do _not_ afflict the ar5iv version.  Note, however, that as arxiv-vanity only has v2 of the paper, rather than v1, it's possible (though I think unlikely) the discrepancies are due to differences in those versions.

Note also that "requesting desktop version" of the page does not fix this problem on mobile even though the webpage renders correctly on an actual desktop.

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 15.2.1
 - Browser: Safari and Chrome

**Comment by dginev** [comment]
Interesting catch, thanks for reporting!

We actually have a completely different math rendering technology in place compared to vanity - they start off from the TeX source latexml annotates in, while we trust its presentation MathML. So you can find very surprising discrepancies between the sites. I'll dig in to find which piece got misplaced...

**Comment by dginev** [comment]
@JessRiedel still waiting for a Chrome update on mobile that lets me preview the articles as native MathML, which should a week or two away.

In the meantime, ar5iv now offers a fallback "STIX Two Math" web font for all devices, so it _should_ render the characters properly on all mobile devices. I'll revisit this comment once my own Android device updates.

**Comment by dginev** [comment]
Actually, it was already possible to update manually today, so I got to check the latest "Chrome for Android" now and the reported characters are properly rendering.

We're not done here yet though. Since we have transitioned to MathML Core, we also need to deal with (hopefully a quick & small) wave of inaccuracies from the markup switchover.

Currently, the bra-ket is not rendered symmetricly, where the bar in particular does not appear to be vertically centered:

![image](https://user-images.githubusercontent.com/348975/213187115-0542c674-50e9-49fd-8e29-ab91a9bd716d.png)

I'll try to pass this up the chain and see which component needs to be updated.

**Comment by dginev** [comment]
I think the current state here is good enough to close this particular issue, but there is likely more refinement to come in the future...

<img src="https://github.com/dginev/ar5iv/assets/348975/e97ae21f-dd89-420f-849c-86eeb824c3c1" width="300px">
