### ISSUE TITLE
Improve article 1711.04436

### ISSUE THREAD

**Issue by I-E-E-E** [dginev/ar5iv#114]
Missing article

**Comment by dginev** [comment]
Sadly, we have no way to fix this in general on our end. The sources for this article contain two files:
```
$ unzip 1711.04436.zip 
Archive:  1711.04436.zip
  inflating: latex.tex               
  inflating: main.pdf 
```

where the PDF is what you see at the arXiv site, and the tex file is the underwhelming:
```tex
\documentclass{article}
\pdfoutput=1
\usepackage{pdfpages}
\begin{document}
\includepdf[pages=-,lastpage=14]{main.pdf}
\end{document}
```

In other words, the document does not have a proper latex source submitted to arXiv, hence ar5iv can not generate the HTML for it.
