### ISSUE TITLE
Social card suggestion: first image = thumbnail

### ISSUE THREAD

**Issue by gwern** [dginev/ar5iv#121]
Somewhat related to #112: the Twittercards could be improved by setting a better thumbnail than the current 

    <meta property="og:image" content="https://ar5iv.labs.arxiv.org/assets/ar5iv_card.png">

Such a generic empty 'Arxiv' thumbnail is arguably little better than no thumbnail at all. (It takes up a lot of space, if nothing else. Look at the Twitter card screenshot, that's like a third of the entire presentation to depict the word 'Arxiv', which is already inserted at the bottom as 'arxiv.org'.)

In a perfect world, paper authors would specify a good thumbnail image designed to encapsulate the paper; but we don't, so the question is, can we do better?

I suggest that there is often an image in a paper which summarizes: the first figure/image.

As a quick test, I looked at the last 5 Arxiv papers in my newsletter. Of them, the first figure in 2 are pretty meh as thumbnails (<https://arxiv.org/pdf/2201.07520.pdf#page=3&org=facebook> <https://arxiv.org/pdf/2112.11848.pdf#page=5>), 1 would be pretty good (<https://arxiv.org/pdf/2202.12211.pdf#google&page=1> / `https://ar5iv.labs.arxiv.org/html/2202.12211/assets/x1.png`) and the remaining 2 are big enough I'd need to see them in action to be sure (<https://arxiv.org/pdf/2201.11503.pdf#page=1> <https://arxiv.org/pdf/2202.08360.pdf#facebook&page=1>). On net, I think showing the first figure as thumbnails would make them work better in a social media setting.

Once implemented, an obvious improvement would be to try to guess based on aspect ratio if an image would be a good thumbnail. The bad one and an uncertain one have like 4:1 W:H (because they are 4 panels side by side), and the other uncertain one is the opposite, 1:8. Requiring thumbnails to be <2:1 or 1:<2  and using the current empty 'Arxiv' placeholder thumbnail would probably remove a lot of bad thumbnails.

Note also that this is a very intuitive and simple rule for picking a thumbnail. It's not some undiscoverable magic figure class or ID like `ar5iv-og:thumbnail`. It's just the simplest thing that could work. If Ar5iv becomes widely used, authors will pick it up subconsciously and start designing their first figure to be a good thumbnail. (And since readership is highly skewed in papers, you only need a few papers to have good thumbnails to benefit a lot of readers.)

---

<https://ar5iv.labs.arxiv.org/html/2112.11848> looks like it's missing most of the paper in the Ar5iv version, FWIW.

**Comment by dginev** [comment]
Will pass that on to the arXiv team, but it looks like it's "not in the cards" for ar5iv. 

Thanks for the thoughtful suggestion in any case, I know arxiv-vanity did a very good effort towards that.

P.S. Good news about `2112.11848`, it now seems to render OK.
