### ISSUE TITLE
Improve article 1910.06709

### ISSUE THREAD

**Issue by mguaypaq** [dginev/ar5iv#124]
**Exact location of issue**

The footnotes of [1910.06709](https://ar5iv.labs.arxiv.org/html/1910.06709#footnote1) (link is to the first footnote).

**Problem details**

Visual problem:
When viewing the article in Firefox on a laptop screen with full screen width, the footnotes appear in the right margin alongside the text (which seems fine) and they are slightly cut-off on the right (which is the problem). It looks as if the last character or so of each line is "under" the scrollbar on the right edge.

Possible fix:
Changing the css property `padding-right` the `ltx_note_outer` class (set on [this line](https://github.com/dginev/ar5iv-css/blob/dd89eb77b4099de7d9b076842ee8caa1cbab4b03/css/ar5iv.css#L519)) from `2rem` to `3rem` produces something acceptable, at least in my browser. I have no idea if this would be a robust fix.

**(Optional) Expected behavior**
I would expect the footnote text to appear in the right margin (as it does now), without overflowing to the right of the visible area.

**Desktop (please complete the following information)**
 - OS: Debian (12/bookworm/testing)
 - Browser: Mozilla Firefox 91.7.0esr

**(Optional) Screenshots**
![Screenshot](https://user-images.githubusercontent.com/928742/160502238-f94c7545-244b-4eed-83f6-2de244514886.png)

**Comment by dginev** [comment]
Thanks for letting me know! The really valuable information for me here @mguaypaq is to know your monitor width and screen resolution. You have one of the few form factors that my `@media` queries waffle through, sorry about that.

**Comment by mguaypaq** [comment]
My screen is 14 inches along the diagonal, 12 inches wide, and my resolution is 1920 x 1200.

**Comment by dginev** [comment]
I did not have any better ideas (or time to do a complete redesign of the side note UI), so I went with your suggestion @mguaypaq . Thanks for the report, and apologies the resolution took so long.
