### ISSUE TITLE
Improve article 2004.09297

### ISSUE THREAD

**Issue by Magnetic2014** [dginev/ar5iv#131]
**Exact location of issue**
Just after the [Introduction section](https://ar5iv.labs.arxiv.org/html/2004.09297v2#S1.p1)

**Problem details**

- All contents after Introduction section are missing while the Abstract and Introduction section look normal.

**Expected behavior**
- All contents should be displayed normally.

**Desktop**
- OS: both macOS and Windows
- Browser: chrome

**(Optional) Screenshots**
![image](https://user-images.githubusercontent.com/14221971/162880800-71fd6f6c-a6dc-4457-a975-b70c217f87a5.png)

**(Optional) Additional context**
- Error log:
  - `Error:expected:\end{document} Input ended while environment document was open`
  - `Error:expected:\fi Input ended while conditional \ifaclfinal was incomplete`
  - `Conversion complete: 2 errors`

**Comment by dginev** [comment]
2004.09297 appears to be fully recovered, now that we are using the latest version and have completed a regeneration with latexml 0.8.7.

Thank you for the report @Magnetic2014 ! Feel free to reopen the issue - or open new ones - whenever you encounter more ar5iv inaccuracies.
