### ISSUE TITLE
Improve article 2203.14101

### ISSUE THREAD

**Issue by yufengwhy** [dginev/ar5iv#132]
**Exact location of issue**
2203.14101

Example:
only half of pdf transformed

**Comment by dginev** [comment]
Since we updated to the latest article versions, 2203.14101 is no longer available. To quote from arXiv, the authors remark:

> Comments: This report has been withdrawn by the authors due to critical issues in Section 2.3.1 of Article 2

So I will close with wontfix, even though we still can't convert the original well.
