### ISSUE TITLE
Improve article 2012.03618 - \hrule

### ISSUE THREAD

**Issue by damaru2** [dginev/ar5iv#137]
**Exact location of issue**
[2012.03618 Algorithm 1](https://ar5iv.labs.arxiv.org/html/2012.03618v4#alg1) Pseudocode contains \hrule that is not displayed correctly

**Problem details**
\hrule should produce a horizontal rule beneath line 3 of the pseudocode but it is displayed to the right

**Desktop (please complete the following information)**
 - OS: Ubuntu
 - Browser Firefox

**Comment by dginev** [comment]
More problems before we get to `\hrule`, I will close here as duplicate to #136 until we surface our way above Fatal territory again.
