### ISSUE TITLE
Improve article 2112.08935

### ISSUE THREAD

**Issue by anubhav4sachan** [dginev/ar5iv#145]
**Exact location of issue**
Not rendering

**Problem details**

Renders template.

**Comment by dginev** [comment]
Thanks for reporting this issue!

We seem to be detecting the wrong source with latexml here - instead of `main.tex`, we convert `bare_jrnl_compsoc.tex`, which as you say is the template file.

This should be easy to correct, especially once we double-check how arXiv decides on the main source for this particular bundle.

**Comment by dginev** [comment]
An update is that I plan to ship a fix for this issue together with #27 , as the two mistakes are related.

I have recently reread the publicly released [AutoTeX](https://metacpan.org/pod/TeX::AutoTeX) and [arXiv::FileGuess](https://metacpan.org/pod/arXiv::FileGuess) repositories, but it seems the reason for picking up `main.tex` over `bare_adv.tex` in 2112.08935 lies elsewhere.

At the moment my best guess for a path forward is to add two small black/whitelists, one banning common template names (the two `bare_` files in this paper) and the other to opt in favor of standard main names (main.tex, ms.tex, paper.tex, etc). However, this is *not* what arXiv does - there are no name lists - so I'm a bit hesitant to implement it before I have someone explain what is really going on in selecting the main TeX source for 2112.08935

**Comment by dginev** [comment]
The plan in my previous comment was executed, the full regeneration of ar5iv took place in December. This article should now be rendering as expected:

https://ar5iv.labs.arxiv.org/html/2112.08935

Thanks for the report @anubhav4sachan ! You're always welcome to open more issues for the remaining ar5iv inaccuracies.
