### ISSUE TITLE
latexml conversion command for ar5iv

### ISSUE THREAD

**Issue by sparkyqin** [dginev/ar5iv#169]
Dear friend,
For this paper https://arxiv.org/abs/nucl-th/0002023v1, I use following command to convert it to html
latexmlc --dest=doc.html mix_delrho
and it thows following waring and error
Warning:unexpected:\bm \bm should only appear in math mode
Error:malformed:ltx:biblist Attempt to close </ltx:biblist>, which isn't open
but when I use ar5iv, https://ar5iv.labs.arxiv.org/html/nucl-th/0002023v1, there is no above waring and error.
So is there something wrong with my command, and may I know the converting command using in ar5iv? Thanks.

**Comment by dginev** [comment]
Hi @sparkyqin ,

The exact conversion for ar5iv is configured and carried out by a worker executable, specifically [latexml_worker L288-L313](https://github.com/dginev/LaTeXML-Plugin-Cortex/blob/master/bin/latexml_worker#L288-L313).

I have been meaning to prepare a Dockerfile that can be used for a turnkey conversion and I will use the occasion of this issue to do so. There are a number of customizations to the default LaTeXML run that are needed for maximizing the success rates over arXiv, as you rightfully suspect in your question.

**Comment by sparkyqin** [comment]
Thanks for your reply, now I see that some customizations are needed, so looking forward to the docker image, it's a very useful work.

**Comment by dginev** [comment]
@sparkyqin the Docker image is now available at [ar5ivist](https://github.com/dginev/ar5ivist)

The turnkey command you can use today is:
```bash
$ docker run -v "$(pwd)":/docdir -w /docdir \
             --user "$(id -u):$(id -g)" \
             latexml/ar5ivist:2208.01 --source=main.tex --destination=html/main.html
```

And the exact latexmlc options for conversion can be inspected at the Dockerfile entrypoint [here](https://github.com/dginev/ar5ivist/blob/main/Dockerfile#L92-L99). Hope this helps!
