### ISSUE TITLE
Improve article cond-mat/0505185

### ISSUE THREAD

**Issue by CreatorZZY** [dginev/ar5iv#173]
**Exact location of issue**
A link [https://arxiv.org/abs/cond-mat/0505185](https://arxiv.org/abs/cond-mat/0505185) is to the source article, point to the hash: `S3.T2.12`.
**Problem details**

 - Wrong table displayed.

**Desktop (please complete the following information)**
 - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36

**(Optional) Screenshots**
![image](https://user-images.githubusercontent.com/38124587/182508957-71987dd0-a78d-4358-9b69-3bf17ff17a86.png)

**Comment by dginev** [comment]
Thank you for the report!

Two ways to see this problem:

1. LaTeXML tries to follow the low-level visual display of the printed page, and adds transform directives that rotate the table for a landscape page. However, it gets the height wrong, so the table collides with the nearby text.
  - This perspective (and checking whether the interplay with flexbox figures is correct) needs latexml development to be resolved.

3. Landscape pages don't really transfer to the ar5iv viewer application, and shouldn't be preserved from the source. 
  - This perspective is usually easy to enforce via CSS rules, and I think I ought to be able to also cover this case - some transforms are already disabled in ar5iv-css.

**Comment by dginev** [comment]
Resolved with the latest CSS update. Here is a link to the Table 2 in question:
https://ar5iv.labs.arxiv.org/html/cond-mat/0505185#S3.T2

Thank you for the report @CreatorZZY !
