### ISSUE TITLE
Improve article 1704.06803

### ISSUE THREAD

**Issue by limengran98** [dginev/ar5iv#175]
**Exact location of issue**

Article fails to render

**Problem details**
```
 Package pgfplots info on input line 18: Using 'lua backend=false' for axis: %
ymode=log unsupported (yet).

Fatal:timeout:if_limit Conditional limit of 699999 exceeded, infinite loop?
```

(edited by DG)

**Comment by dginev** [comment]
Thank you for the report! Looks like our support for pgfplots needs an upgrade.

**Comment by dginev** [comment]
The article now successfully converts to HTML with the latest update to ar5iv.

It appears to be only missing `{overpic}` support. But we have other issues tracking that, so I will close here.
