### ISSUE TITLE
Improve article 1505.00444

### ISSUE THREAD

**Issue by luttrell** [dginev/ar5iv#20]
**Exact location of issue**
Equation 3 of https://ar5iv.org/html/1505.00444#S2.E3

**Problem details**
The original LaTeX source code (generated by LyX) \left\Vert ... \right\Vert has been replaced by \left\| ... \right\| in the ar5iv version, which then displays only the "filler" ... between the | ... |.

Example:
None.

**Expected behavior**
The original LaTeX source code (generated by LyX) \left\Vert ... \right\Vert should generate || ... ||, which is a double vertical line at the left and right of the bracketed expression

**Desktop (please complete the following information)**
 - OS = MacOS
 - Browser = Safari

**Comment by dginev** [comment]
Thanks for the report @luttrell !

The PDF has equation 3 rendered as:
![image](https://user-images.githubusercontent.com/348975/213190474-30cf26a3-004a-4fcc-b511-ccc29a8ab55c.png)

And ar5iv today has it as (on Firefox):
![image](https://user-images.githubusercontent.com/348975/213190635-d8fb69a0-62cb-479a-becf-eab18717bc61.png)

Is this good enough to close the issue?

Also, there is a separate fidelity problem in Chrome, where the parentheses are stretched out to be too large, which is pending a resolution in [mathml-core#103](https://github.com/w3c/mathml-core/issues/103).

But if the original problem is now remediated, we can close here.

**Comment by luttrell** [comment]
I reported this several years ago, and I have only a vague recollection of the original details.

I do not recall exactly what was incorrectly rendered before, nor can I find it using a search based on the details in your email’s subject line, though the rendering quoted in your email looks correct to me.

Could you point me to whatever it was that I originally reported?

Stephen Luttrell
West Malvern, UK
***@***.***

**Comment by dginev** [comment]
Hi @luttrell ,

My apologies, this may be confusing if you are interacting with my comment via email. The original comment was written in Github's issue interface, which you can find here:

https://github.com/dginev/ar5iv/issues/20

The issue has a link to the original article, to your detailed remarks (thank you again!), and to a couple of screenshots I added for today's rendering of the specific equation in question.

**Comment by luttrell** [comment]
Oh! That was only a year ago, but it seemed like much longer ago to me.

I drilled down to check the LaTeX in https://ar5iv.org/html/1505.00444#S2.E3 <https://ar5iv.org/html/1505.00444#S2.E3> which is now \left\| . . . \right\|, and this renders the equation correctly.
 
The issue now appears to have been fixed. Thank you.

Stephen Luttrell
West Malvern, UK
***@***.***

**Comment by dginev** [comment]
Great to hear, and thank you for the quick response!

Time flies around here too. You're always welcome to report more ar5iv issues when you encounter them, even if you just happen to remember by chance years from today.
