### ISSUE TITLE
Improve article 2104.13225

### ISSUE THREAD

**Issue by gchrupala** [dginev/ar5iv#24]
**Exact location of issue**

Todo note, such as: https://ar5iv.org/html/2104.13225v3#todo1

**Problem details**

These todo notes should not be displayed, as the sources disables them via 

> \usepackage[disable]{todonotes}

**Comment by dginev** [comment]
Thank you for reporting this @gchrupala ! I have excluded the article in question from the public viewing, until we have the issue resolved.

My apologies again.

**Comment by dginev** [comment]
@gchrupala we have added proper support for disabled todo-notes, whenever you have time feel free to re-examine the article you mentioned at:

https://ar5iv.org/html/2104.13225

Please let me know if the original problem is resolved.

I see latexml reports a remaining unsupported package, tipa.sty, and a resulting undefined macro `\textipa`. I can take a quick look at supporting that before closing this issue fully.

**Comment by gchrupala** [comment]
Thanks, todonotes looks good now. 
Supporting \textipa would be nice too, but that's relatively minor.
