### ISSUE TITLE
Improve article 2108.07232

### ISSUE THREAD

**Issue by jowens** [dginev/ar5iv#260]
**Exact location of issue**
Anywhere `LaTeXdescription` is used

Example:
> Section 1 (intro) has a `LaTeXdescription`

**Problem details**

`LaTeXdescription` is not parsed and hence the text is not presented as a list and the description content is not printed at all.

**Desktop**
MacOS, Chrome
<img width="646" alt="_2108_07232__Better_GPU_Hash_Tables" src="https://user-images.githubusercontent.com/976970/196055579-a9324df4-bdd8-4953-afd1-2f5d3a388616.png">

**Comment by dginev** [comment]
Merged into #259
