### ISSUE TITLE
support 00README: articles 2107.01510, 2110.07698 

### ISSUE THREAD

**Issue by arashbm** [dginev/ar5iv#27]
**Exact location of issue**
Everywhere. The wrong latex file is being shown.

**Problem details**
[ArXiv handels supplementary materials](https://arxiv.org/help/submit_tex#autoignore) by compiling them and concatenating them at the end of the main PDF (as determined by `toplevelfile` in the [`00README.XXX`](https://arxiv.org/help/00README#toplevel) file.

Currently, Ar5iv does not seem to care about a `00README.XXX` file, and (at least for the following examples) compiles only the supplementary materials and presents it as the main paper.

Examples:
- 2107.01510  on [ArXiv](https://arxiv.org/pdf/2107.01510.pdf) vs [Ar5iv](https://ar5iv.org/html/2107.01510)
- 2110.07698 on [Arxiv](https://arxiv.org/pdf/2110.07698.pdf) vs [Ar5iv](https://ar5iv.org/pdf/2110.07698)

**Expected behavior**

At a minimum, if there is a  `00README.XXX` file that has a `toplevelfile` declared, ar5iv should try compiling that and leave everything else ignored.

At best it should also compile all other LaTeX files and other text file that are not ignored, either by `00README.XXX` or by having `%auto-ignore` as the first line, and finally present them at the end of the main file after the references.

**Comment by dginev** [comment]
Really happy to see this report, I was not at all familiar with the `00README.XXX` convention. Should be easy to fix!

**Comment by dginev** [comment]
I am happy to report `00README.XXX` is now supported, and the articles contain their main texts.

They don't convert perfectly yet, but we can close this issue - feel free to open new issues for additional problems!
