### ISSUE TITLE
Cannot render on webpage using the same code

### ISSUE THREAD

**Issue by BensenHsu** [dginev/ar5iv#285]
@dginev Which engine do you use to render the ar5iv webpage? I tried to use Mathjax to render the formula on a website with the same code: `A_{ij}^{G}:=\left\{\begin{tabular}[c]{ll}$1$&if $(ij)\in E^{G},$\\ $0$&otherwise.\end{tabular}\right.`, but it didn't work. Besides, there are also some other issues related to rendering formulas, so I'm wondering what do you use to render formulas flawlessly. Much appreciated!

arXiv ID: quant-ph/0504224v1

Screenshot: 
<img width="711" alt="image" src="https://user-images.githubusercontent.com/51500098/201723836-312bf2f8-586d-4dc7-9d90-0f59ea8485eb.png">

**Comment by dginev** [comment]
Hey @BensenHsu ,

The underlying HTML pages in ar5iv use MathML markup for all equations, which was generated by [latexml](https://github.com/brucemiller/LaTeXML/). You can examine the [ar5ivist](https://github.com/dginev/ar5ivist) Dockerfile for the exact command that transforms LaTeX into HTML5 behind the scenes.

Also, if you use ar5iv with Firefox the browser will just render the MathML natively, but we indeed currently rely on client-side MathJax in e.g. browsing with Chrome.

In your example, a `{tabular}` environment may be beyond the allowed scope of default "mathjax-LaTeX" (or may require configuration or...), so requesting client-side rendering over the raw TeX may fail. In ar5iv, latexml will first map the `{tabular}` to web-native MathML (I believe usually `<mtable>` elements for such a case) and MathJax can then render the simpler MathML construct. 

There are many possible ways to write down a table in LaTeX, in many separate packages (such as longtable, deluxetable, tabu ...), but only a single `<mtable>` element in MathML. That is usually a good reduction in complexity.

**Comment by dginev** [comment]
I have updated [ar5ivist](https://github.com/dginev/ar5ivist) yesterday, the `2301.01` release now uses latexml 0.8.7 and the latest ar5iv CSS.

We are also starting to rely on native MathML Core in 2023, as of Chrome 109 offering support (and all other browsers expected to follow suit).

I will close the issue here for now, but feel free to ping me if any questions remain.
