### ISSUE TITLE
Improve article 2109.04981

### ISSUE THREAD

**Issue by cranmer** [dginev/ar5iv#3]
**Exact location of issue**
Renders with no spaces for some reason

https://ar5iv.org/html/2109.04981

This is a super cool project! Thanks for your work!

**Comment by cranmer** [comment]
If it helps, here's another article in the same journal template (perhaps a different version) that doesn't have the problem:
https://arxiv.org/abs/1902.09914

**Comment by dginev** [comment]
Excellent, thanks for reporting this Kyle @cranmer !

**Comment by dginev** [comment]
We've started a nice discussion in #4 so I'll close here as a duplicate - feel free to jump over there.
