### ISSUE TITLE
Improve article 2012.14913

### ISSUE THREAD

**Issue by manoja328** [dginev/ar5iv#328]
**Exact location of issue**
- images not displayed
- location not correct

**Comment by dginev** [comment]
The clipping here looks identical to #327 , likely a recent regression with the ar5iv web service. Will take a look - thanks for the report!

**Comment by dginev** [comment]
This has been resolved with the latest web service update (now also with a new SSL certificate)

Thanks again for the report @manoja328 ! Feel free to open issues for any other problems you encounter.
