### ISSUE TITLE
Improve article 2303.10798

### ISSUE THREAD

**Issue by suncho6502** [dginev/ar5iv#338]
The article failed to convert.

Fatal:timeout:if_limit Conditional limit of 1499999 exceeded, infinite loop?
 at eTeX.pool.ltxml; line 81
 In Core::Definition::Conditional[\ifcsna... /usr/local/share/perl/5.34.0/LaTeXML/Package/eTeX.pool.ltxml; line 81
(Building...
(Loading compiled schema /usr/local/share/perl/5.34.0/LaTeXML/resources/RelaxNG/LaTeXML.model... 0.02 sec) 0.43 sec)
(Rewriting... 0.00 sec)
(Finalizing... 0.02 sec)
Conversion complete: 1 warning; 1 error; 1 fatal error; 1 undefined macro[\extrafloats]

**Comment by dginev** [comment]
Thanks for the report! Had opened #337 to save you some work, linking the two and closing.
