### ISSUE TITLE
UI: +shortcut link to PDF version

### ISSUE THREAD

**Issue by gwern** [dginev/ar5iv#377]
Ar5iv pages should provide a prominent link directly to the PDF version. A good way to do this would be a [PDF SVG icon](https://gwern.net/static/img/icon/pdf.svg) placed after the title.

When a reader clicks on an Ar5iv link from social media or my site, there are generally only three things they will do (in roughly descending frequency): (1) close the tab / go back; (2) read the HTML version; (3) read the PDF version instead.

The first two are easy & well-supported; the third is not. Currently, a reader must already know to scroll potentially hundreds of screens to the end of the page, click on the 'View original on arXiv' link (the 6th of 7 links, listed after what are apparently much more important links, such as 'read a literally random paper' or 'go to the completely unrelated paper which happened to be uploaded a second before this one'), load, wait, find the sidebar, click on 'PDF', then load and wait some more, and then one can finally start reading. One reason I am reluctant to link Ar5iv instead of /abs/ is that for the common case of wanting to read the PDF, Ar5iv makes it such a PITA to actually get to the PDF; while /abs/ shows the abstract and makes the PDF easy to get. And yet, if Ar5iv made the PDF as easy to get as /abs/, it would for almost all purposes be strictly superior to /abs/: everyone gets to read the abstract as quickly & easily as /abs/, while PDF users are no worse off (having to tap 1 easily-located link at the top of the page to read the PDF) and mobile/HTML readers enjoy easy scrolling down to keep reading.

This can be fixed easily by simply including a little PDF icon after the title which is a hyperlink to the respective PDF file on Arxiv proper. This is a decades-old WWW idiom that everyone understands, looks fine, takes up near-zero space, saves a ton of effort in one of the most common use-cases, and is easy to implement.

**Comment by dginev** [comment]
Hey @gwern , thanks for the request.

The current plan for ar5iv is to enter a "phasing out" stage in Fall, as arXiv launches their public HTML beta on the main site. We will start redirecting to the main arXiv HTML pages.

As long as that goes through as planned, there won't be any use cases for us to keep improving the current ar5iv pages. But if for some reason ar5iv needs to remain operational long-term, your request is sensible!

I am trying to work in lockstep with the main arXiv team, and indeed I suspect their preference will continue to be to link to the `/abs/` pages long-term.

**Comment by gwern** [comment]
Wherever the Arxiv HTML version lives, it's going to need to link to the /abs/ & PDF at the top for the reasons I've outlined. Does theirs already do that or should I be copying this bug somewhere else?

**Comment by dginev** [comment]
@gwern I think you'll have to wait for their public Beta announcement and then send them a copy of this to a new repository they'll open for feedback. I'll share the "arXiv integration 1" issue list with them, so they may also read through the details here in advance.

**Comment by gwern** [comment]
OK. Guess we'll just have to wait & see.
