### ISSUE TITLE
this paper doesn't seem to load 1707.06347

### ISSUE THREAD

**Issue by davidenitti** [dginev/ar5iv#379]
**Exact location of issue**
https://ar5iv.labs.arxiv.org/html/1707.06347
**Problem details**
no text

**Comment by dginev** [comment]
Thank you for the report!

The arXiv submission never included a real TeX source, just a technique to ingest a precompiled PDF. The source in question here is:

```tex
\documentclass[a4paper]{article}
\pdfoutput=1
\usepackage{hyperref}
\hypersetup{
  pdfinfo={
    Title={},
    Author={}
  }
}
\usepackage{pdfpages}

\begin{document}
\includepdf[pages=1-last]{ppo-min.pdf}
\end{document}
```

This is identical to the problem in #376 , and sadly we have no avenue to resolution from the ar5iv side. The only realistic change is for the arXiv to resubmit an update basewd on the actual TeX of the article, for arXiv to compile through.

So I am resolving with "wontfix" for now.
