### ISSUE TITLE
include a table of content

### ISSUE THREAD

**Issue by elipapa** [dginev/ar5iv#387]
Amazing work!
Browsing long html articles would be made much easier if there was a table of content sidebar.

**Comment by dginev** [comment]
Hi @elipapa , thank you for the kind words.

One could certainly make an auto-generated TOC sidebar. I think arXiv have started experiment with that, as you can see while exploring the current beta HTML articles at:
https://info.arxiv.org/about/accessibility_html_papers.html

Which leads me to the issue resolution - currently the ar5iv focus is on extending coverage and improving the conversions of articles to HTML, less so developing new UI/UX features. We expect a transition where arXiv is the primary source of HTML in the coming months and the web service here will start redirecting to the main site. Keep an eye out for that, as they are also interested in technical feedback.

Thanks again!
