### ISSUE TITLE
Improve article 2104.00602 - it converted "3" into "2.000000"

### ISSUE THREAD

**Issue by konstantinua00** [dginev/ar5iv#390]
**Exact location of issue**
Please provide a link to the source article, ideally pointing to the exact piece of content containing the issue. Our documents have "id" attributes on each logical element.

Section 2 Figure 5 of [article I clicked "Report issue" on and which number got automatically inserted into the title.](https://ar5iv.labs.arxiv.org/html/2104.00602#S2)   
How do I look up "id attribute" on mobile?

**Problem details**

Converter wrote wrong number in the Figure - in PDF and on other branches of the tree first prime number is `3`, but on the root and right branch in HTML it wrote `2.000000`.  
Left branches have powers over the `3`, root and right one do not.

**(Optional) Expected behavior**
`3`

**Smartphone (please complete the following information):**
 - Device: Redmi 7A
 - OS: Android 10
 - Browser: Opera, Firefox

**Comment by dginev** [comment]
Thank you for the report!
A quick pass over the figure allowed me to grab a minimal example that has this problem:

```tex
\documentclass{article}
\usepackage{tikz}
\usetikzlibrary{math}

\begin{document}

\begin{tikzpicture}[scale=0.9]
  \foreach\i in{0}{
    \tikzmath{\x=int(3^(\i+1));}\node[below]at(0.5-2*\i,-1-\i){${\x}$};
  }
\end{tikzpicture}

\end{document}
```

It looks like latexml's pgf-math support has a subtle error in evaluating `\x=int(3^(\i+1));`.

This is a very useful catch - thanks again.

**Comment by dginev** [comment]
The original report was resolved - but this is still a very good article to test SVG+MathML interplay for browser testing.

ar5iv was recently updated to use latexml v0.8.8, and I am walking issues and closing ones with improvements. You are welcome to open a new issue any time for remaining problems.
