### ISSUE TITLE
Improve article 2107.13738

### ISSUE THREAD

**Issue by npc-dev** [dginev/ar5iv#40]
**Exact location of issue**
[Table 1](https://ar5iv.org/html/2107.13738#S3.T1.1)

Example:
[Column 1, row 1 of Table 1](https://ar5iv.org/html/2107.13738#S3.T1.1.1.1.1.2) shows text saying "\rowcolor[gray]0.8" - that text is a LaTeX command that should not be visible.

**Problem details**
The "\rowcolor[gray]0.8" LaTeX command appears in the visible text of a table. This LaTeX command should not be shown as text in the HTML page.

**Desktop**
 - OS: Manjaro Linux
 - Browser: Firefox

**Comment by dginev** [comment]
I believe this has been resolved after the latest update. Thanks for the report!
