### ISSUE TITLE
Improve article 2309.07864 (forest.sty)

### ISSUE THREAD

**Issue by Dozengame** [dginev/ar5iv#421]
https://ar5iv.labs.arxiv.org/html/2309.07864v3

Conversion to HTML had a Fatal error and exited abruptly. This document may be truncated or damaged.

**Comment by dginev** [comment]
Looking at the [log](https://ar5iv.labs.arxiv.org/log/2309.07864), the article requires `forest.sty` support. The failure comes from an error cascade due to lacking support for that package.

**Comment by dginev** [comment]
Closing as duplicate to #409 to do some bookkeeping, thanks for the report!
