### ISSUE TITLE
Improve article 2303.02491v2

### ISSUE THREAD

**Issue by SriAR** [dginev/ar5iv#423]
**Exact location of issue**
id="algorithm1"

Example:
> https://browse.arxiv.org/html/2303.02491v2#algorithm1

**Problem details**

Newline rendering in algorithm2e: the pdf has newlines in the algorithm while the html doesn't. This I assume is because of the "\;".
 
**(Optional) Expected behavior**
The algorithm should have newlines.

**Desktop (please complete the following information)**
 - OS: Arch Linux
 - Browser: Firefox 

**(Optional) Additional context**
What is the recommended way to add algorithms to papers in latex to make it accessible?

**Comment by dginev** [comment]
Thanks for the report. It looks like latexml needs better support for `\;` used in this algorithm2e context

Small example:
```tex
\documentclass{article}
\usepackage{algorithm2e}
\begin{document}
\begin{algorithm}
\DontPrintSemicolon
line 1\;
line 2\;
line 3\;
\For{$t = 1, 2, \ldots, T$} {
    line 1\;
    line 2\;
    line 3\;
}
\end{algorithm}
\end{document}
```

**Comment by dginev** [comment]
I think this is now resolved in the latest ar5iv update:
https://ar5iv.labs.arxiv.org/html/2303.02491v2

It may take a little while for the arXiv HTML to get refreshed, but I think I can close here. Thanks for the report!
