### ISSUE TITLE
Improve article 2210.00581

### ISSUE THREAD

**Issue by Cl00m** [dginev/ar5iv#427]
**Exact location of issue**

Article fails to convert

**Problem details**

According to [the log](https://ar5iv.labs.arxiv.org/log/2210.00581), it appears the LaTeX 3 interpretation fails badly here, an unknown `\ExplSyntaxOn` being the first error.

**Comment by dginev** [comment]
Thanks for the report! I updated the issue description with the details.

**Comment by dginev** [comment]
After a fresh reconversion of ar5iv with latexml v0.8.8, this is now resolved - the article gets healthy HTML:

https://ar5iv.labs.arxiv.org/html/2210.00581
