### ISSUE TITLE
Improve article 2308.15517

### ISSUE THREAD

**Issue by mllife** [dginev/ar5iv#442]
**Exact location of issue**
Article failed to convert.

**Problem details**
TeX source not found.

**Comment by dginev** [comment]
Thanks for the report. As the arXiv main article link indicates, there is no TeX source available:
https://arxiv.org/abs/2308.15517

ar5iv can only create HTML from TeX/LaTeX sources, and it is beyond the scope of our tools to convert PDF to HTML. Maybe one day arXiv will have an in-house OCR approach for those cases.

So I have to close with "wontfix" here.
