### ISSUE TITLE
Improve article 2305.04359

### ISSUE THREAD

**Issue by VoVAllen** [dginev/ar5iv#445]
**Exact location of issue**
Please provide a link to the source article, ideally pointing to the exact piece of content containing the issue. Our documents have "id" attributes on each logical element.

Example:
> Section 3 of [math/0003013](https://ar5iv.org/html/math/0003013#S3.p2), where the link points to the fragment `#S3.p2`

**Problem details**

The html is old version, not the latest version

**Comment by dginev** [comment]
Thank you for the report.

I just completed an update to the latest article versions, so this should be rectified after the next full reconversion of ar5iv, likely in early April.

But generally ar5iv does not promise the latest version of an article, it is beyond the scope of the project to keep the collection constantly up to date. That is something that will be provided by the official arXiv HTML, soon after ar5iv is retired. So I'll close with wontfix, even though an update is planned to happen.
