### ISSUE TITLE
Improve article 1707.06347

### ISSUE THREAD

**Issue by JimXiongGM** [dginev/ar5iv#451]
Unable to display content

<img width="940" alt="Snipaste_2024-03-06_19-22-59" src="https://github.com/dginev/ar5iv/assets/16780394/1fb56c97-56ff-47d7-a6b9-a7eace0f208b">

**Comment by dginev** [comment]
Thank you for the report!

This we can't fix on our end I'm afraid. The author has seemingly intentionally added a PDF asset and provided a TeX file that includes that directly - effectively making it impossible for TeX-based converters to produce HTML.

Here is the source for this article:
```tex
\documentclass[a4paper]{article}
\pdfoutput=1
\usepackage{hyperref}
\hypersetup{
  pdfinfo={
    Title={},
    Author={}
  }
}
\usepackage{pdfpages}

\begin{document}
\includepdf[pages=1-last]{ppo-min.pdf}
\end{document}
```

The only latexml-related fix would be for the author to re-upload, using the actual source for the article.
