### ISSUE TITLE
Improve article 2210.07194

### ISSUE THREAD

**Issue by sqkadmin** [dginev/ar5iv#453]
**Exact location of issue**

Article fails to convert.

**Comment by dginev** [comment]
Thank you for the report - I edited the description.

Good news: It appears that the current regeneration of ar5iv will resolve the issue, ([early preview here](https://corpora.mathweb.org/preview/arxmliv/tex_to_html/2210.07194)). I will do another check when the new conversion goes live in a couple of weeks.

**Comment by dginev** [comment]
Indeed, some HTML is now available - will resolve here, but feel free to report more issues as you spot them.
