### ISSUE TITLE
Improve article 1711.02437

### ISSUE THREAD

**Issue by chaozg** [dginev/ar5iv#47]
**Exact location of issue**
> Eqution 1 of [math/1711.02437](https://ar5iv.org/html/1711.02437)

**Problem details**
> Latex equation is not rendered (with red warning: 'Math input error').

**Desktop (please complete the following information)**
 - OS: Ubuntu
 - Browser: chrome

**Comment by dginev** [comment]
Something to investigate with our client-side rendering of math. On Firefox this looks reasonable I think?

![image](https://user-images.githubusercontent.com/348975/152785495-7409c751-ddcb-414f-b1ae-d07074a8123b.png)

**Comment by cztuc** [comment]
Yes, everything is OK with Firefox, but not with Chrome.

**Comment by dginev** [comment]
There is a suspicious fragment in the MathML here which probably causes the error:
```xml
<mtext mathcolor="red">
  <span class="ltx_rule" style="width:0.0pt;height:10.8pt;background:black;display:inline-block;"></span>
</mtext>
```

We should check if it's a generation error, given it is not shown in any way in the PDF rendering. 

This could be a subtle interpretation bug with latexml -- thank you for catching it and bringing it to our attention!

**Comment by dginev** [comment]
I think with the latest update to Chrome 109, this issue is resolved. We are now serving native MathML Core in Chrome.
