### ISSUE TITLE
Live paper conversion

### ISSUE THREAD

**Issue by tom-doerr** [dginev/ar5iv#479]
Could we get quick conversion of Arxiv papers? The papers I'm reading often aren't yet converted by ar5iv. Is there a reason for this?

**Comment by dginev** [comment]
This is asked periodically and indeed there is a good answer. Referencing https://github.com/dginev/ar5iv/issues/398#issuecomment-1772836598

In short, ar5iv focuses on the latexml conversion, and does not intend to compete with the main arXiv site. So there was little to no effort invested in rebuilding realtime features, or even staying up-to-date with the article version (see #48 ).

This was helpful getting us to a point where the [transition into arXiv](https://blog.arxiv.org/2023/12/21/accessibility-update-arxiv-now-offers-papers-in-html-format/) is now underway. The expectation is that when arXiv has stabilized HTML for its entire article collection, the ar5iv Lab will be sunset, by becoming a redirect service into the arXiv official HTML.

Thank you for the question!
