### ISSUE TITLE
Use latest article versions

### ISSUE THREAD

**Issue by apaleyes** [dginev/ar5iv#48]
**Exact location of issue**
https://ar5iv.org/abs/2108.04105
https://arxiv.org/abs/2108.04105

**Problem details**
ar5iv worked perfectly on this document, amazing work team! The only issue is that the arXiv original was updated to a second revision. Both title and content on ar5iv are out of date. Would be great if https://ar5iv.org/abs/2108.04105 was showing second version and not the first one. Can this be done?

Note: this is related to #10 however I would expect, maybe naively, to see the most recent version of an article.

Thanks!

**Comment by dginev** [comment]
I certainly agree with the underlying problem -- I would also prefer to have had the most recent version of all arXiv articles. This hinges on a technicality, where the distributed sources are not updated, so [most of them](https://arxiv.org/help/bulk_data_s3) stick at v1.

I'll keep the issue open waiting for the ultimate resolution of the issue -- if ar5iv is adopted under the arXiv umbrella, I can put in the work to serve the latest version, without relying on those source bundles. Until it is, I would like to avoid an appearance of competing with their live site, so I will stick to whichever version was found in the republished sources.

Thanks for the request!

**Comment by apaleyes** [comment]
Makes sense!

Would it be possible to update the ar5iv version manually though, on request? Similarly to what is already done with deletions?

**Comment by dginev** [comment]
Deletions make ar5iv look even less competitive to arXiv, which is why I have no issue with them. Manually updating to the newest version brings the question, again, of - "is ar5iv trying to be a live preview site?"

I would like to take all the energy from "this site would be amazing if it used the latest versions" and direct it at the arXiv team -- "hey, if you work with ar5iv, they'll make it much better". I think that's a win-win-win proposition.

**Comment by apaleyes** [comment]
sensible position, thanks for taking the trouble to explain it

**Comment by dginev** [comment]
Work is now underway to do the switch to using latest article versions here, together with transitioning to a "live preview" service.

I hope the live site will be ready for the start of 2023.

**Comment by dginev** [comment]
What we've come to terms with is that the right place for versioned article HTML is the arXiv site itself, which is [underway](https://blog.arxiv.org/2023/12/21/accessibility-update-arxiv-now-offers-papers-in-html-format/).

I do one-off updates at times for ar5iv, the latest on was on February 22, 2024. Articles updated before that date should have their latest versions available. ar5iv is now on a path to getting retired, as arXiv brings all of the HTML in-house, so I will close here.
