### ISSUE TITLE
  Projects arXiv User Support  AH-106072   Paper withdraw 2309.16442

### ISSUE THREAD

**Issue by jdmagyar** [dginev/ar5iv#488]
Dear Sirs,
I withdraw the paper named "A Small World of Bad Guys: Investigating the Behavior of Hacker Groups in Cyber-Attacks", but it can still be accessed at https://ar5iv.labs.arxiv.org/html/2309.16442. Is it feasible to take it out?
Best regards,
Antonio Iovanella

**Comment by dginev** [comment]
Thank you for the request. I have removed the paper from the ar5iv backend. We need to wait a little until the Fastly cache expires, should be gone in some hours. I will close the issue when I see it disappear.

**Comment by dginev** [comment]
Looks expired now, thanks again.
