### ISSUE TITLE
Improve article [arXiv:1606.00999]

### ISSUE THREAD

**Issue by pkoppenb** [dginev/ar5iv#5]
**Exact location of issue**
Md frame around [Fig 1](https://ar5iv.org/html/1606.00999#S1.F1), and several others.

**Problem details**

mdframed environment is not displayed.

**Smartphone (please complete the following information):**
 - Device: Nokia 8]
 - OS: Android
 - Browser firefox

**Comment by dginev** [comment]
cross-linking [latexml #1483](https://github.com/brucemiller/LaTeXML/issues/1483) here.

**Comment by dginev** [comment]
I have added experimental mdframed.sty support for ar5iv, and the article in question seems to render its framed figures better.

Thanks for the report @pkoppenb , and feel free to reopen if you encounter any other issues.
