### ISSUE TITLE
Improve article 1611.03530

### ISSUE THREAD

**Issue by mylwx** [dginev/ar5iv#509]
[**Exact location of issue**
https://arxiv.org/abs/1611.03530
**Problem details**
Full translation not available

**Desktop (please complete the following information)**
 - OS: Windows
 - Browser EDGE

![image](https://github.com/user-attachments/assets/3e1c56c8-ae8d-4f9a-b66c-a37a0851e37f)

![image](https://github.com/user-attachments/assets/f4b62b56-5e4b-4177-857e-3b3d61c68ebd)

arxiv article title: 
Understanding deep learning requires rethinking generalization

**Comment by dginev** [comment]
This document only includes a PDF asset, wrapped in TeX with:

```tex
\begin{document}
\includepdf[pages=1-last]{alyosha.pdf}
\end{document}
```

So it falls outside of possible coverage for ar5iv, which converts TeX to HTML. For this paper we need an approach based on PDF OCR, which for now is not in scope.
