### ISSUE TITLE
Scope of ar5iv?

### ISSUE THREAD

**Issue by realliyifei** [dginev/ar5iv#514]
Hi, I am doing RAG based on ar5iv. What is the scope of it (particularly the time cutoff)? Does it includes almost all the arXiv papers, including the super old ones?

**Comment by dginev** [comment]
Hi @realliyifei ,

Yes, arXiv includes a single version of all arXiv articles, going all the way back to the beginning. It trails the live site by a month - the update for the November `2411.*` articles is just happening today and will be live in the evening. This has been the pattern for the last couple of years.

So if you need the latest articles immediately, you should look into the arXiv-native HTML. If you are OK being a month behind, ar5iv should be sufficient coverage.

Lastly, there is a bundled dataset available upto April, which you can find [here](https://sigmathling.kwarc.info/resources/ar5iv-dataset-2024/)
