### ISSUE TITLE
Improve article 2201.05989

### ISSUE THREAD

**Issue by kwonminki** [dginev/ar5iv#57]
**Exact location of issue**
Please provide a link to the source article, ideally pointing to the exact piece of content containing the issue. Our documents have "id" attributes on each logical element.

Example:
> Section 3 of [math/0003013](https://ar5iv.org/html/math/0003013#S3.p2), where the link points to the fragment `#S3.p2`

**Problem details**

 - is the article missing pieces of content (a section, an abstract, references?)
 - are there latex constructs missing support (marked in red), or supported inaccurately?
 - is the visual appearance flawed - pieces of content colliding, placed or sized wrongly?

Example:
> Labels are missing their targets, and conversion fails abruptly.

**(Optional) Expected behavior**
A clear and concise description of what you think the preferred outcome should be.

**Desktop (please complete the following information)**
 - OS: [e.g. iOS, Windows, Ubuntu]
 - Browser [e.g. firefox, chrome, safari]

**Smartphone (please complete the following information):**

**(Optional) Screenshots**

**(Optional) Additional context**

**Comment by dginev** [comment]
Thank you for the report! I have re-edited the description and reopened, since it's certainly a broken rendering.

**Comment by dginev** [comment]
The article has now improved to an Error status, but we still need new support for `epic.sty` and `pgfcalendar.sty` to get it to a successful state.
