### ISSUE TITLE
"Table of contents" for quick nagivation

### ISSUE THREAD

**Issue by cailiang9** [dginev/ar5iv#65]
Is it possible to add TOC for quick navigation among article sections?

**Comment by dginev** [comment]
The short answer is - yes.

The long answer involves how exactly one should design and implement that.

I am deferring such advanced "article viewer" features until a little later in the project lifetime, until a day where we have a claim to arXiv-compatibility. Then we could decide this with the arXiv team discussing alongside us.

**Comment by dginev** [comment]
arXiv's HTML has an implementation of that, and Mark recently reminded me that latexmlpost has a `--navigationtoc` option.

I think we'll skip both of these for ar5iv, as the site will be retired soon, but arXiv will likely keep the table of contents for their viewer.
