### ISSUE TITLE
predefine font-family for windows 10~11 from ar5iv site

### ISSUE THREAD

**Issue by cailiang9** [dginev/ar5iv#68]
It will be nice to set default font-family for windows 10~11 from ar5iv site, because default font-family on win is not well adjusted as on mac.

**Comment by dginev** [comment]
Sounds like an issue for the styling side at [ar5iv-css](https://github.com/dginev/ar5iv-css). We can keep this open here.

Could you share a screenshot of what you see on your windows device?
Also, hopefully, the font _family_ is explicitly set on all platforms. It is defined in the two CSS variables here:
https://github.com/dginev/ar5iv-css/blob/main/css/ar5iv.css#L7-L8

**Comment by cailiang9** [comment]
default with Microsot Yahei :
<img width="648" alt="image" src="https://user-images.githubusercontent.com/3636844/153761996-6ea7995b-b8b3-4c23-bcd6-7fb45c7f4ed2.png">

adjusted with Lucia bright font:
<img width="656" alt="image" src="https://user-images.githubusercontent.com/3636844/153761920-962ca964-ad83-4da1-8b56-7872284dbc76.png">

**Comment by dginev** [comment]
Excellent to have these screenshots, thank you! Some more deliberate preparation seems to be necessary then. Either to get Noto distributed within ar5iv, or to choose a good Windows fallback...

**Comment by cailiang9** [comment]
> Sounds like an issue for the styling side at [ar5iv-css](https://github.com/dginev/ar5iv-css). We can keep this open here.
> 
> Could you share a screenshot of what you see on your windows device? Also, hopefully, the font _family_ is explicitly set on all platforms. It is defined in the two CSS variables here: https://github.com/dginev/ar5iv-css/blob/main/css/ar5iv.css#L7-L8

seems Noto does not match Cambria Math very well:
<img width="648" alt="image" src="https://user-images.githubusercontent.com/3636844/153791679-93a0ed6c-3c13-46aa-8653-1225db91de48.png">

Maybe need to use Lucida, Times New Rome  instead, or change Cambria Math to other font

**Comment by dginev** [comment]
Hi @cailiang9 ! Could you take a look at https://ar5iv.org/html/1801.04381 and check if your system can load the intended Noto fonts now? I just deployed a method to serve them together with the article content.

If this works as intended, the abstract should appear as:
![image](https://user-images.githubusercontent.com/348975/154163877-ef5d64b4-dc54-44cf-87f7-65c1efc11cf3.png)

**Comment by dginev** [comment]
Excellent, thank you for confirming.
