### ISSUE TITLE
Improve article 1109.3786

### ISSUE THREAD

**Issue by sbaumard** [dginev/ar5iv#70]
**Exact location of issue**

First equation of section 2 of [math/1109.3786](https://ar5iv.org/html/1109.3786#S2)

**Problem details**

An xymatrix has not been converted.

**Desktop (please complete the following information)**
 - OS: Manjaro
 - Browser : Firefox

**(Optional) Additional context**

**Comment by dginev** [comment]
Also cross-referencing here with latexml's [#450](https://github.com/brucemiller/LaTeXML/issues/450).

**Comment by dginev** [comment]
We now have "intermediate" support for XY diagrams, and the xymatrix in question has been converted.

We still have some further upgrades to do w.r.t accurate sizing and spacing in certain contexts, but I think this should be enough to close this particular issue.

Thanks for the report @sbaumard !

**Comment by sbaumard** [comment]
This fix seems rather satisfactory, thanks ! Although, other than sizing and spacing, it seems that dark mode compatibility should also be checked.
