### ISSUE TITLE
Improve article 1310.5833

### ISSUE THREAD

**Issue by sbaumard** [dginev/ar5iv#71]
**Exact location of issue**

1. Subsection 2.2 of [math/1310.5833](https://ar5iv.org/html/1310.5833#S2) ;
2. First equation of annex A of [math/1310.5833](https://ar5iv.org/html/1310.5833#A1).

**Problem details**

Respectively :

1. an xymatrix has not been converted ;
2.  some vector graphics have not been rendered,

**Desktop (please complete the following information)**
 - OS: Manjaro
 - Browser : Firefox

**Comment by dginev** [comment]
Thanks!

Cross-referencing with latexml's [#450](https://github.com/brucemiller/LaTeXML/issues/450). We currently are missing xy support and need to develop it to properly display this article.

**Comment by dginev** [comment]
We have updated all arXiv article sources to the latest versions back in December, and it looks like this particular one has been retracted, with the message:

"Replaced by the English version, [arXiv:1510.05549](https://arxiv.org/abs/1510.05549)"

as you can see here:
https://arxiv.org/abs/1310.5833

So I will close this issue with essentially a "wontfix".

Let me know if you'd like me to look into 1510.05549, maybe we can continue there?

**Comment by sbaumard** [comment]
An eyeball check for 1510.05549 yields no particular issues, thanks !
