### ISSUE TITLE
Article 2104.05240: v2 exists, but generated HTML is from v1

### ISSUE THREAD

**Issue by rspeer** [dginev/ar5iv#88]
**Exact location of issue**

The problem is in https://ar5iv.labs.arxiv.org/html/2104.05240#bib . The References section contains a correction of a citation that was made between v1 and v2 and is not reflected in the ar5iv copy.

**Problem details**

Article https://ar5iv.labs.arxiv.org/html/2104.05240 is generated from https://arxiv.org/abs/2104.05240 . The arXiv URL points to v2, because the authors of the article cited me incorrectly in v1.

Changing the "x" to a "5" produces an HTML5 version of v1 of the article, which contains this incorrect citation. I cannot find an HTML5 version of v2.

**(Optional) Expected behavior**

ar5iv pages should be made from the latest arXiV version of a paper, not the earliest.

**Desktop (please complete the following information)**
 - OS: Windows
 - Browser: Firefox

**(Optional) Additional context**

This is a problem that I and others discussed with Deyan Ginev when he deployed the prototype of ar5iv. He acknowledged the problem and was concerned about it, but at the time he said that he had no ability to fix the problem because he didn't have access to all of arXiV's versions, only a data export that contained the v1 of each article.

He indicated that if ar5iv were to become an official arXiv project, it would have access to the correct data and be able to render the latest version of each article.

**Comment by dginev** [comment]
Cross-referencing the general "enable lastest versions" issue #48  here, thank you for letting me know!

We are now on a path to updating our sources to the latest available ones in arXiv, but it may take a little time.

**Comment by dginev** [comment]
I'll close here, since #48 is enough for tracking the problem.
