### ISSUE TITLE
Improve article 2108.10457

### ISSUE THREAD

**Issue by Strilanc** [dginev/ar5iv#89]
**Exact location of issue**

12 lines before the very end of the article, in [the very last code listing](https://ar5iv.labs.arxiv.org/html/2108.10457#A4.p4), the command \ttb is rendered as text instead of being used to adjust formatting.

![image](https://user-images.githubusercontent.com/79941/155014584-7015c451-fb80-496e-9c46-a42d0af6655c.png)

**Expected behavior**

No "\ttb" text shown.

**Desktop**

 - OS: Windows.
 - Browser: Firefox.

**Comment by dginev** [comment]
It looks like `\ttb` is now no longer an issue here - thanks for the report @Strilanc !

Feel free to open new issues whenever you encounter any ar5iv inaccuracies.
