### ISSUE TITLE
Improve article 2104.09792

### ISSUE THREAD

**Issue by hkboo** [dginev/ar5iv#94]
**Exact location of issue**
Please provide a link to the source article, ideally pointing to the exact piece of content containing the issue. Our documents have "id" attributes on each logical element.

Example:
> Section 3 of [math/0003013](https://ar5iv.org/html/math/0003013#S3.p2), where the link points to the fragment `#S3.p2`

**Problem details**

 - is the article missing pieces of content (a section, an abstract, references?)
 - are there latex constructs missing support (marked in red), or supported inaccurately?
 - is the visual appearance flawed - pieces of content colliding, placed or sized wrongly?

Example:
> Labels are missing their targets, and conversion fails abruptly.

**(Optional) Expected behavior**
A clear and concise description of what you think the preferred outcome should be.

**Desktop (please complete the following information)**
 - OS: [e.g. iOS, Windows, Ubuntu]
 - Browser [e.g. firefox, chrome, safari]

**Smartphone (please complete the following information):**

**(Optional) Screenshots**

**(Optional) Additional context**

**Comment by dginev** [comment]
Actually this is a good one to investigate, thanks @hkboo - I'll reopen.

**Comment by dginev** [comment]
It has to do with a redefinition of `\text` and/or a use of pgfplots that leads latexml into an infinite loop.

**Comment by dginev** [comment]
This article now converts to a [healthy state](https://ar5iv.labs.arxiv.org/html/2104.09792), using the ar5iv update generated via latexml v0.8.8
